# shell is non-interactive, done
if [ -z "$PS1" ]; then
	return
fi

# debugging
#set -x

# get operation system for further action or just fail afterwards :P
case ${OSTYPE} in
	darwin*)
		export OS=Darwin
		;;
	linux*)
		export OS=Linux
		;;
esac

# set path to environment home
if [ ${EUID} -eq 0 ]; then
	case ${OS} in
		Darwin)
			export ENV_HOME=/Users/${SUDO_USER}
			;;
		Linux)
			export ENV_HOME=/home/${SUDO_USER}
			;;
	esac
else
	export ENV_HOME=${HOME}
fi

# set path prefix
case ${OS} in
	Darwin)
		if [ -x /usr/local/bin/brew ]; then
			export PATH_PREFIX=/usr/local
		fi
		if [ -x /opt/local/bin/port ]; then
			export PATH_PREFIX=/opt/local
		fi
		;;
	Linux)
		export PATH_PREFIX=""
		;;
esac


# set path to environment docs
export ENV_DOC=${ENV_HOME}/.env

# set path to public bash docs
if [ -d ${ENV_DOC}/public/etc/bash.d ]; then
	export BASH_DOC=${ENV_DOC}/public/etc/bash.d
fi

# load bash docs
if [ -d ${BASH_DOC} ]; then
	for FILE in prompt options exports functions aliases term; do
		if [ -r ${BASH_DOC}/${FILE} ]; then
		. ${BASH_DOC}/${FILE}
		fi
	done
fi

# set path to local bash docs
if [ -d ${ENV_DOC}/local/etc/bash.d ]; then
	export BASH_DOC_LOCAL=${ENV_DOC}/local/etc/bash.d
fi

# load local bash docs
if [ -d ${BASH_DOC_LOCAL} ]; then
	for FILE in prompt options exports functions aliases term; do
		if [ -r ${BASH_DOC_LOCAL}/${FILE} ]; then
		. ${BASH_DOC_LOCAL}/${FILE}
		fi
	done
fi

# load bash completion docs
if [ -f ${PATH_PREFIX}/etc/bash_completion ]; then
		. ${PATH_PREFIX}/etc/bash_completion
fi

# vim: set filetype=sh :
