" dotrc-env@blackox.org

" only vim, no vi compatibility
set nocompatible

" runtime env
set runtimepath=$HOME/.vim.d,$VIMRUNTIME

" syntaxhighlighting
syntax on

" colorscheme
if &term != 'linux'
	set t_Co=256
	colorscheme distinguished
endif

" numbering
set number

" whitespace
set list

" whitespace characters
set lcs=tab:»·
set lcs+=trail:·
set lcs+=precedes:«
set lcs+=extends:»
"set lcs+=eol:¶
set lcs+=nbsp:·

" tabulator
set noexpandtab
set tabstop=4
set shiftwidth=4

" indenting
set autoindent
if has("autocmd")
	filetype plugin indent on
endif

" history
set history=50

" cursor position
set ruler

" backspace delete char
set backspace=2

" status, cmdline
set statusline=%f\ (%{&ff})\ (%Y)\ [%{strftime(\"%d/%m/%y\ -\ %H:%M\")}]\ [%l,%v]\ [%p%%]\ %m%r%h
set laststatus=2
set cmdheight=2

" backup
set backup
set backupdir=$HOME/.vim/backup
set directory=$HOME/.vim/swap

" session
set sessionoptions=blank,buffers,folds,help,options,tabpages,winsize

" filetype
filetype on
filetype plugin on

" print options
set popt=paper:A4

" textwidth
set textwidth=78

" highlight search
set hlsearch

" key mapping
map <F5> :cprev <CR>
map <F6> :cnext <CR>
noremap <F4> :set hlsearch! hlsearch?<CR>

" bash like completion
set wildmode=longest,list

" code completion
autocmd InsertLeave * if pumvisible() == 0|pclose|endif
set ofu=syntaxcomplete#Complete

let b:includefile = $HOME . "/.env/local/etc/vimrc"
if (filereadable(b:includefile))
	exe 'source' b:includefile
endif
