#!/bin/bash

# environment docs path
ENV_DOC=$(cd ${0%/*} && echo ${PWD%})

# ready to initialize
ENV_INIT="${ENV_DOC}/.init"
[ -e ${ENV_INIT} ] && {
	echo "dotrc-env initialize already done" >&2
	exit 1
}

# get base path
ENV_BIN="${ENV_DOC}/bin"
ENV_ETC="${ENV_DOC}/etc"

# make bin dir
HOME_BIN="${HOME}/bin"
[ ! -d $HOME_BIN ] && {
	mkdir $HOME_BIN
}

# create symlinks
for SRC in $(find $ENV_BIN -type f); do
	SRC=${SRC##*/}
	DST=$SRC
	ln -sf "${ENV_BIN}/${SRC}" "${HOME}/bin/${DST}"
done
for SRC in $(find $ENV_ETC -maxdepth 1); do
	SRC=${SRC##*/}
	[ $SRC == ${ENV_ETC##*/} ] && {
		continue
	}
	DST=${SRC%.*}
	ln -sf "${ENV_ETC}/${SRC}" "${HOME}/.${DST}"
done

# lock initialize
touch $ENV_INIT

# vim: set ft=sh :
