# shell is non-interactive, done
if [ -z "$PS1" ]; then
	return
fi

# debugging
#set -x

# get operation system for further action or just fail afterwards :P
case ${OSTYPE} in
	darwin*)
		export OS=Darwin
		;;
	linux*)
		export OS=Linux
		;;
esac

# get user home


# set path to environment docs
case ${OS} in
	Darwin)
		export ENV_DOC=/Users/tschaefer/.env
		;;
	Linux)
		export ENV_DOC=/home/tschaefer/.env
		;;
esac

# set path to bash docs
if [ -d ${ENV_DOC}/etc/bash.d ]; then
	export BASH_DOC=${ENV_DOC}/etc/bash.d
fi

# set path to local bash docs
if [ -d ${ENV_DOC}/etc/local/bash.d ]; then
	export LOCAL_BASH_DOC=${ENV_DOC}/etc/local/bash.d
fi

# load bash docs
if [ -d ${BASH_DOC} ]; then
	for FILE in prompt options exports functions aliases; do
		if [ -r ${BASH_DOC}/${FILE} ]; then
		. ${BASH_DOC}/${FILE}
		fi
	done
fi

# load local bash docs
if [ -d ${LOCAL_BASH_DOC} ]; then
	for FILE in prompt options exports functions aliases; do
		if [ -r ${LOCAL_BASH_DOC}/${FILE} ]; then
		. ${LOCAL_BASH_DOC}/${FILE}
		fi
	done
fi

# load bash completion docs
case ${OS} in
	Darwin)
		if [ -f /opt/local/etc/bash_completion ]; then
			. /opt/local/etc/bash_completion
		fi
		;;
	Linux)
		if [ -f /etc/bash_completion ]; then
			. /etc/bash_completion
		fi
		;;
esac

# vim: set filetype=sh :
