"" environment
set nocompatible
set runtimepath=${HOME}/.vim,$VIMRUNTIME
filetype plugin indent on

runtime! configs/basic.vim
runtime! configs/mappings.vim
runtime! configs/plugins.vim

let s:rc  = getcwd() . '/.local.vim'
let s:sig = getcwd() . '/.local.vim.asc'
if filereadable(s:rc) && filereadable(s:sig)
    let null = system('gpg --verify ' . s:sig . ' ' . s:rc)
    if v:shell_error == 0
        exe 'source' s:rc
    endif
endif
